### ISSUE TITLE
Error: Cannot find module '@storybook/global'

### ISSUE THREAD

**Issue by vadhe** [literalpie/storybook-framework-qwik#32]
I Have an existing Qwik project, so I run this npx storybook@next init --type html --parser ts but I'm getting error
<img width="1076" alt="Screen Shot 2023-01-23 at 09 24 51" src="https://user-images.githubusercontent.com/36479850/213951964-e3897e9b-04d6-4e00-bf46-580215372bd7.png">

**Comment by literalpie** [comment]
Hmm, I wish I could help you but this isn't much information to go on. Does the command work if you do it in a different project? (try doing `npm init` in a temp folder, then running the storybook init command again)

Actually, this seems to be happening before my framework is even use, so if anything, this might be a storybook issue.

**Comment by vadhe** [comment]
yeah, you're right the error should come from the storybook it selfitself. so I try to run without @next to `next storybook init --type html --parser ts,` and it works.
