### ISSUE TITLE
Can't find main.js file

### ISSUE THREAD

**Issue by luisamlopez** [literalpie/storybook-framework-qwik#39]
By following the instructions to use this framework, I encounter the issue of being unable to run the project because there wasn't a `main.js` file. This is the error thrown: 

```
path\node_modules\@storybook\core-common\dist\index.js:9
    `),!mainConfigPath)throw new Error(import_ts_dedent.dedent`
                             ^
Error: No configuration files have been found in your configDir (path\.storybook).
Storybook needs "main.js" file, please add it (or pass a custom config dir flag to Storybook to tell where your main.js file is located at).
    at validateConfigurationFiles (path\node_modules\@storybook\core-common\dist\index.js:9:30)
```

**Comment by literalpie** [comment]
If the `npx storybook init` command works, there should be a `.storybook/main.ts` file in your project. Does this exist for you? Did the init command add storybook to your `package.json`?

**Comment by luisamlopez** [comment]
Yes, it did but the error says that a .js file is needed, not a .ts

**Comment by literalpie** [comment]
I think the error message is just imprecise. `main.ts` works every time for me.

Is there any chance you can share a repo where you're getting this error? It's hard to track down the issue with the information you've given.

In the main.ts file you were given, does it reference "storybook-framework-qwik"?

If you create a brand new qwik project and run the storybook init command in that, does that work as expected?

**Comment by literalpie** [comment]
Also, please send me the output of `npx sb@next info `

**Comment by luisamlopez** [comment]
The output of `npx sb@next info` is: 

```
Environment Info:

  System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
  Binaries:
    Node: 18.14.0 - C:\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 9.3.1 - C:\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (110.0.1587.50)
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-beta.54 => 7.0.0-beta.54
    @storybook/addon-links: ^7.0.0-beta.54 => 7.0.0-beta.54
    @storybook/blocks: ^7.0.0-alpha.8 => 7.0.0-alpha.8
```

I created a repo following the same steps: [https://github.com/luisamlopez/component-library-storybook](https://github.com/luisamlopez/component-library-storybook) 

**- In the main.ts file you were given, does it reference "storybook-framework-qwik"?** Yes it does 

**- If you create a brand new qwik project and run the storybook init command in that, does that work as expected?** Yes, it runs normally, but I can't run: `npm run storybook`

**Comment by literalpie** [comment]
The reproduction seems to work fine on my Mac. I'll try on a Windows machine when I get a chance.

**Comment by literalpie** [comment]
Well, I'm not seeing the issue in Windows either 😕 

To see the issue, you're just doing `npm install` and `npm run storybook`, right?

**Comment by luisamlopez** [comment]
For some reason, I tried again in another repo initialized as a QwikCity project and it worked! I'm going to close this, thank you for your help!
