### ISSUE TITLE
storybook-framework-qwik has no exported member 'Preview'

### ISSUE THREAD

**Issue by staykova-sport-thieme** [literalpie/storybook-framework-qwik#52]
Hello! I am working on upgrading to Storybook 7 and adding storybook-framework-qwik to our existing Storybook + Qwik solution.
After adding storybook-framework-qwik, there is the preview.tsx file with the following: 
`export const preview: Preview = {`
 ` parameters: {`
   ` actions: { argTypesRegex: '^on[A-Z].*' },`
   ` controls: {`
     ` matchers: {`
      `  color: /(background|color)$/i,`
      `  date: /Date$/`
 `}}}};`

that requires Preview but it is not exported.
<img width="908" alt="Screenshot 2023-04-25 at 14 39 33" src="https://user-images.githubusercontent.com/75254865/234279664-aaa50663-f6b0-47f5-b056-b79f8a9b6dee.png">

Now I just don't add the type.

**Comment by literalpie** [comment]
Hi, what version are you seeing this issue in? I think I added the Preview export in version `0.2.0`

**Comment by staykova-sport-thieme** [comment]
@literalpie thanks! It was indeed the version (0.1.0), in 0.2.0 it is exported.
