### ISSUE TITLE
Autodocs description from component props type is missing

### ISSUE THREAD

**Issue by staykova-sport-thieme** [literalpie/storybook-framework-qwik#53]
Hello! I guess this is another missing feature regarding autodocs (along with https://github.com/literalpie/storybook-framework-qwik/issues/37). 
Given the ButtonProps here as an example, https://github.com/literalpie/storybook-framework-qwik/blob/main/packages/storybook-framework-qwik/template/cli/button.tsx, all props have a comment which Storybook adds as a desription in the autogenerated docs page.
<img width="500" alt="Screenshot 2023-04-25 at 14 52 53" src="https://user-images.githubusercontent.com/75254865/234283834-97c85b89-5700-4cbf-a5e4-3e40bc4f7b28.png">

**Comment by staykova-sport-thieme** [comment]
This an example of how it should look like, sorry for the misunderstanding.

**Comment by staykova-sport-thieme** [comment]
@literalpie was this also fixed in 0.2.0? I upated to 0.2.0 and the descriptions are there now, thanks!

**Comment by literalpie** [comment]
Oh yes. 0.2.0 was the first version with docs support. Glad it works now!
