### ISSUE TITLE
Failed to resolve import "@qwik-city-sw-register"

### ISSUE THREAD

**Issue by Nick-Mazuk** [literalpie/storybook-framework-qwik#62]
When I try to use anything from Qwik City (either through the decorator or using a Qwik City component like `<Link>`), I get the following error:

```
[vite] Internal server error: Failed to resolve import "@qwik-city-sw-register" from "node_modules/.pnpm/@builder.io+qwik-city@1.2.6/node_modules/@builder.io/qwik-city/index.qwik.mjs?v=51532b32". Does the file exist?
```

## Debug steps

- Referenced at the examples in this repo, even copy-pasting much of the code.
- Referenced through https://github.com/BuilderIO/qwik/pull/2381
- Inlined some of the source code for this plugin (e.g., the decorator)
- Updated to the most recent version of everything.

## Reproduction steps

1. Run `pnpx create-qwik-nx@latest`.
2. Run `nx generate qwik-nx:lib`.
3. Run `nx generate qwik-nx:storybook-configuration`.
4. Add a basic story for the generated component.
5. Uncomment the `qwikCityDecorator` in the generated `preview.ts` file.
6. Run `nx storybook <component-library-target>`.
7. Open storybook in your browser and view the error.

I made a reproduction here: https://github.com/Nick-Mazuk/storybook-nx-qwik

To see the error in my reproduction, just run `nx storybook components` and open your browser to Storybook.

## Related

- https://github.com/BuilderIO/qwik/issues/2669
- https://github.com/BuilderIO/qwik/pull/2381

**Comment by literalpie** [comment]
Thanks for opening this issue with all the details! 

It's definitely a valid issue. I haven't focused on qwik-city support in a while, so it's possible this is a simple oversight or a larger issue.

I'll try to look into this at some point, but I won't guarantee anything. Of course contributions are welcome if anyone comes across this who has ideas!

**Comment by literalpie** [comment]
Hi, sorry it took so long for me to get back to you on this. I believe your issue was that you are trying to access qwik-city things in a lib project, which doesn't have the `qwikCity` Vite plugin. 

It's a little frustrating that `MockQwikCityProvider` still requires the Vite plugin, but that's a Qwik limitation, not anything to do with this library.

**Comment by ppusapati** [comment]
Any update on this issue?
