### ISSUE TITLE
Vite error when adding to fresh Qwik project

### ISSUE THREAD

**Issue by iancharlesdouglas** [literalpie/storybook-framework-qwik#63]
When a new Qwik project is created (using `npm create qwik@latest`  and choosing the first option) and `storybook-framework-qwik` is added to it, the following error is displayed in the console:
```
08:28:40 [vite] Internal server error: Unexpected `FunctionDeclaration` in code: only import/exports are supported
  Plugin: storybook:mdx-plugin
  File: /home/ian/dev/javascript/qwik-storybook/src/stories/Configure.mdx:undefined:undefined
```

The rendered Storybook UI then shows a skeleton that never loads completely:

![image](https://github.com/literalpie/storybook-framework-qwik/assets/3481593/4cb5f721-6fb9-4be5-8eec-75271c5c872b)

**Comment by literalpie** [comment]
Sorry for the delay fixing this. A fix for this has been released! Please let me know if you have more issues.
