### ISSUE TITLE
useVisibleTask$ not working

### ISSUE THREAD

**Issue by O-Hooman** [literalpie/storybook-framework-qwik#65]
I noticed something, it seems useVisibleTask$ not working (the code inside is not executed) but useTask$ is working, I wonder if this is because it's inside the iframe, or no SSR, or no serialization happens, or there's something wrong with my code

Simple example: 
```
useVisibleTask$(() => {
    console.log('ok')
})
```

**Comment by O-Hooman** [comment]
Notes: tried on qwik@1.1.5 and it's working but not @1.2.8

**Comment by literalpie** [comment]
Oof, I'm really stumped about this one. I confirmed that the qwik loader is still being added correctly, and I don't see any difference in the code that gets added to storybook between the two versions.

As said above, 1.1.5 works as expected. I also tested 1.2.0 and that does not work, so there must be something in that minor version release.

There was a time in the past where Qwik had [an issue](https://github.com/BuilderIO/qwik/issues/3945) similar to this. However, unlike that time, `vite --mode dev` works as expected here. I don't know what could be different between a dev mode build and storybook - they both just use the qwik `render` function.

**Comment by O-Hooman** [comment]
> Oof, I'm really stumped about this one. I confirmed that the qwik loader is still being added correctly, and I don't see any difference in the code that gets added to storybook between the two versions.
> 
> As said above, 1.1.5 works as expected. I also tested 1.2.0 and that does not work, so there must be something in that minor version release.
> 
> There was a time in the past where Qwik had [an issue](https://github.com/BuilderIO/qwik/issues/3945) similar to this. However, unlike that time, `vite --mode dev` works as expected here. I don't know what could be different between a dev mode build and storybook - they both just use the qwik `render` function.

Yeah kind of weird, I'll try to find a workaround and report it to qwik as an issue maybe the problem is from the qwik itself

**Comment by O-Hooman** [comment]
Hi @literalpie from this issue discussion (https://github.com/BuilderIO/qwik/issues/5157) I wonder if the problem is this:

* there's qwikloader on newest qwik
![chrome_lCekCo9Ju5](https://github.com/literalpie/storybook-framework-qwik/assets/25758563/86e25c05-9610-4014-90e0-e0b907208cb7)
* and it's load on:qvisible
![chrome_R72gKsJKpk](https://github.com/literalpie/storybook-framework-qwik/assets/25758563/595d28e8-cc59-44a4-84f1-c64334f457f8)

**Comment by Comedalte** [comment]
I got this working by having the render parent being part of the dom before I run it. In other words, it should work after moving down this [line](https://github.com/literalpie/storybook-framework-qwik/blob/main/packages/storybook-framework-qwik/src/preview.ts#L22) until after the parent container is appended to the dom (line 24).
