### ISSUE TITLE
Add dependency @storybook/addon-actions to starter

### ISSUE THREAD

**Issue by iancharlesdouglas** [literalpie/storybook-framework-qwik#66]
When Storybook is added to a Qwik project, the dependency `@storybook/addon-actions` is not added to the dependencies so actions are not registered on the Actions tab for a component.  (Workaround: add the dependency manually.)

**Comment by literalpie** [comment]
Aww man, I didn't realize that the this was causing errors on the starter. Unfortunately, adding dependencies to SB templates isn't as easy as you would expect (would require changes to SB itself, not just this addon). I think the better approach would be to finish #16 or remove the actions from the starter.

**Comment by literalpie** [comment]
This should be fixed in 0.3.0! I'm so sorry that it took a long time to fix this, I know it probably doesn't make a good first impression for anyone who ran into it.
