### ISSUE TITLE
Update to latest

### ISSUE THREAD

**Issue by shilman** [literalpie/storybook-framework-qwik#76]
Hey @literalpie ! A community member just updated `storybook-solidjs` to Storybook 8 and that framework now uses `@storybook/test` per our recommendation.

See: https://github.com/storybookjs/storybook/pull/29514

Qwik is the last holdout. If you're able to get it updated, that means we can clean out that little codepath in the CLI. 😄

**Comment by literalpie** [comment]
@shilman Done!
